[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sss_token = "CgvFp3RNTC9SCpbHqP3KjzRLMd1SckdoWDynqfcQDvA3"
sss_transfer_hook = "F1aUaKxYyCRWJLW7oeAiHNFk2WFJhS2NTm7LdGh8zuSz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
